### ISSUE TITLE
why doesn't my tool interface have the same HPS style ,texture src as yours?

### ISSUE THREAD

**Issue by D-Mad** [kwan3854/CEB_ECON#3]
You:

![Screenshot from 2023-06-27 13-26-15](https://github.com/kwan3854/CEB_ECON/assets/8207507/cec7d7a1-cf20-400a-a985-dfa97aa1b415)

Me:
![Screenshot from 2023-06-27 13-25-02](https://github.com/kwan3854/CEB_ECON/assets/8207507/21460dc4-0c07-437e-a157-fc2ca8a02a7b)

**Comment by kwan3854** [comment]
During the filming of the tutorial, everything functioned normally. However, a bug appeared in the option section when the ECON project was updated. As a result, I had to reluctantly update our Blender plugin code to disable this option after filming, and upload the updated code. Since there have been many updates to ECON since I uploaded my plugin code, I plan to run an update to reactivate this option after checking it in the future.
